# Generated by Django 4.2.14 on 2024-07-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParticipants', models.IntegerField(default=4)),
                ('round', models.IntegerField(default=1)),
                ('participant', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.IntegerField(default=5)),
                ('player_y', models.IntegerField(default=225)),
                ('opponent_x', models.IntegerField(default=730)),
                ('opponent_y', models.IntegerField(default=225)),
                ('ball_x', models.IntegerField(default=750)),
                ('ball_y', models.IntegerField(default=350)),
                ('ball_speed_x', models.IntegerField(default=-5)),
                ('ball_speed_y', models.IntegerField(default=0)),
                ('scored', models.BooleanField(default=True)),
                ('typeOfMatch', models.CharField(default='rg', max_length=2)),
                ('round', models.IntegerField(default=1)),
                ('scorePlayer', models.IntegerField(default=0)),
                ('scoreOpponent', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
