# Generated by Django 4.2.13 on 2024-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_of_message',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
